import { GoogleGenAI } from "@google/genai";
import prisma from "../lib/prisma.js";
import { debug } from "../lib/debug.js";
import { ART_STYLE, ART_STYLE_REMINDER, buildImageStyleGuide } from "./imageStyleGuide.js";
import fs from "fs";
import path from "path";
import { randomUUID } from "crypto";

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_AI_KEY });

const IMAGES_DIR = path.resolve("public/images");

if (!fs.existsSync(IMAGES_DIR)) {
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
}

function saveBase64Image(base64Data: string, mimeType: string = "image/png"): string {
  const ext = mimeType.includes("webp") ? "webp" : mimeType.includes("jpeg") ? "jpg" : "png";
  const filename = `${randomUUID()}.${ext}`;
  const filepath = path.join(IMAGES_DIR, filename);
  const buffer = Buffer.from(base64Data, "base64");
  fs.writeFileSync(filepath, buffer);
  return `/images/${filename}`;
}

function readImageAsBase64(imageUrl: string): { data: string; mimeType: string } | null {
  const imgPath = path.join("public", imageUrl);
  if (!fs.existsSync(imgPath)) return null;
  const data = fs.readFileSync(imgPath).toString("base64");
  const ext = path.extname(imgPath).slice(1);
  const mimeType = ext === "webp" ? "image/webp" : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : "image/png";
  return { data, mimeType };
}

/**
 * Extract the generated image from a Gemini response.
 */
function extractImage(response: any): string | null {
  const candidates = response?.candidates;
  if (!candidates?.[0]?.content?.parts) return null;

  for (const part of candidates[0].content.parts) {
    if (part.inlineData?.data) {
      return saveBase64Image(part.inlineData.data, part.inlineData.mimeType || "image/png");
    }
  }
  return null;
}


/**
 * Generate a single character model sheet using Gemini (for regeneration).
 */
export async function generateCharacterSheet(
  characterId: string
): Promise<string> {
  const character = await prisma.character.findUniqueOrThrow({
    where: { id: characterId },
    include: { universe: true },
  });

  debug.image(`Generating character sheet for "${character.name}" via Gemini`);
  const startTime = Date.now();

  const prompt = buildCharacterSheetPrompt(character);
  const parts: any[] = [{ text: prompt }];

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["Image", "Text"],
    },
  });

  debug.image("Gemini response:", {
    candidates: response?.candidates?.length || 0,
    parts: response?.candidates?.[0]?.content?.parts?.length || 0,
    partTypes: response?.candidates?.[0]?.content?.parts?.map((p: any) => p.text ? "text" : p.inlineData ? `image(${p.inlineData.mimeType})` : "unknown").join(", ") || "none",
    finishReason: response?.candidates?.[0]?.finishReason || "unknown",
    text: response?.candidates?.[0]?.content?.parts?.find((p: any) => p.text)?.text?.slice(0, 200) || "none",
  });

  const imageUrl = extractImage(response);
  if (!imageUrl) {
    throw new Error("No image generated by Gemini for character sheet");
  }

  await prisma.character.update({
    where: { id: characterId },
    data: { referenceImageUrl: imageUrl },
  });

  debug.image(`Character sheet for "${character.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
  return imageUrl;
}

/**
 * Generate ALL character sheets for a universe. Each character gets its
 * own independent Gemini call to prevent visual blending between characters.
 * Style consistency is maintained via identical style guide text in each prompt.
 */
export async function generateAllCharacterSheets(
  universeId: string
): Promise<void> {
  const characters = await prisma.character.findMany({
    where: { universeId },
    include: { universe: true },
    orderBy: { role: "asc" }, // main first
  });

  if (characters.length === 0) return;

  debug.image(`Generating ${characters.length} character sheets (separate sessions)`);

  for (let i = 0; i < characters.length; i++) {
    const character = characters[i];

    if (character.referenceImageUrl) {
      debug.image(`"${character.name}" already has sheet, skipping`);
      continue;
    }

    debug.image(`Sheet ${i + 1}/${characters.length}: generating for "${character.name}"`);
    const startTime = Date.now();

    const prompt = buildCharacterSheetPrompt(character);

    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: {
          responseModalities: ["Image", "Text"],
        },
      });

      const imageUrl = extractImage(response);
      if (!imageUrl) {
        debug.error(`No image in Gemini response for "${character.name}"`);
        continue;
      }

      await prisma.character.update({
        where: { id: character.id },
        data: { referenceImageUrl: imageUrl },
      });

      debug.image(`Sheet for "${character.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
    } catch (e: any) {
      debug.error(`Sheet failed for "${character.name}": ${e.message}`);
    }
  }

  debug.image("All character sheets generated");
}

/**
 * Build the prompt text for a character model sheet.
 */
function buildCharacterSheetPrompt(character: any): string {
  const outfitSection = character.outfit
    ? `\nOUTFIT (character is ALWAYS wearing/carrying ALL of these):\n${character.outfit}`
    : "";

  return `${ART_STYLE}

REPEAT: NO OUTLINES. NO LINEWORK. Shapes are defined by SOFT SMUDGED COLOR ONLY.

Create a page of SOFT CHALK PASTEL STUDIES of this character. Show this character 12-15 times on a warm cream-colored paper background. Mix of full body views and close-up head/upper body views. Each study should look like an individual chalk pastel drawing — soft, powdery, dreamy. NOT a clean technical model sheet. NOT a cartoon turnaround. These are PASTEL STUDIES, like pages from an artist's sketchbook done entirely in soft chalk pastel.

IMPORTANT: This character is a ${character.speciesOrType}. Follow the body description below EXACTLY. This character has its own unique body shape, colors, proportions, and clothing.

CHARACTER: ${character.name}
SPECIES: ${character.speciesOrType}

BODY (follow this description precisely — this defines what the character looks like):
${character.appearance}
${outfitSection}
SPECIAL DETAIL: ${character.specialDetail}

Include:
- Full body: front, side, back, 3/4, running, sitting, reaching
- Close-up: happy, sad, surprised, determined, laughing

CONSISTENCY: The character must look identical in every study. Same proportions, colors, features. All clothing/accessories visible in every view. Wings, tails, antennae never disappear. Head shape stays the same in close-ups.

ONE character painted many times in oil pastel. NOT multiple characters. NOT outlined cartoon art.`;
}

/**
 * Generate a location reference sheet using Gemini.
 */
export async function generateLocationSheet(
  locationId: string,
  previousSheetUrls: string[] = []
): Promise<string> {
  const location = await prisma.location.findUniqueOrThrow({
    where: { id: locationId },
    include: { universe: true },
  });

  const moods = ["gentle", "funny", "exciting", "mysterious"];
  const randomMood = moods[Math.floor(Math.random() * moods.length)];
  const styleGuide = buildImageStyleGuide(
    randomMood,
    location.universe.illustrationStyle
  );

  debug.image(`Generating location sheet for "${location.name}" via Gemini`);
  const startTime = Date.now();

  const prompt = `${ART_STYLE}

Create a LOCATION REFERENCE SHEET. Show this location 8-10 times on a plain white background.

LOCATION: ${location.name}
ROLE: ${location.role}
DESCRIPTION: ${location.description}
LIGHTING: ${location.lighting}
KEY LANDMARKS (must appear every time): ${location.landmarks}

Include:
- Wide panoramic view
- Medium view at character scale
- Close-up of key landmark
- Morning light version
- Afternoon/golden hour version
- Night/dusk version
- View from approaching
- View from inside/center looking out

CONSISTENCY: Same landmarks, geography, and colors across all views. No characters. Environment only.

ONE location shown from many angles and times of day. NOT multiple locations.`;

  const parts: any[] = [];

  for (const sheetUrl of previousSheetUrls) {
    const img = readImageAsBase64(sheetUrl);
    if (img) {
      parts.push({ inlineData: { data: img.data, mimeType: img.mimeType } });
    }
  }

  if (previousSheetUrls.length > 0) {
    parts.push({
      text: `The images above are reference sheets from the same book. Match their exact art style.`,
    });
  }

  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["Image", "Text"],
    },
  });

  const imageUrl = extractImage(response);
  if (!imageUrl) {
    throw new Error("No image generated by Gemini for location sheet");
  }

  await prisma.location.update({
    where: { id: locationId },
    data: { referenceImageUrl: imageUrl },
  });

  debug.image(`Location sheet for "${location.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
  return imageUrl;
}

/**
 * Generate ALL scene illustrations for a story using a single multi-turn
 * chat session. Gemini maintains character, scenery, and style consistency
 * across all pages because they're generated in the same conversation.
 *
 * Flow:
 * 1. First message: all character/location reference sheets + style guide
 * 2. Each subsequent message: one page's scene prompt → one illustration
 */
export async function generateStoryImages(
  universeId: string,
  characterIds: string[],
  mood: string,
  pages: { page_number: number; image_prompt: string; characters_in_scene?: string[] }[],
  onProgress?: (pageNum: number, total: number, imageUrl: string) => void
): Promise<Map<number, string>> {
  const styleGuide = buildImageStyleGuide(mood);
  const results = new Map<number, string>();

  // Build character descriptions
  const characters = await prisma.character.findMany({
    where: { universeId, id: { in: characterIds } },
  });

  let charDesc = "";
  for (const char of characters) {
    charDesc += `${char.name} (${char.speciesOrType}): ${char.appearance}`;
    if (char.outfit) charDesc += `. Outfit: ${char.outfit}`;
    if (char.specialDetail) charDesc += `. ${char.specialDetail}`;
    charDesc += "\n";
  }

  // Build location descriptions
  const locations = await prisma.location.findMany({ where: { universeId } });
  let locDesc = "";
  for (const loc of locations) {
    locDesc += `${loc.name}: ${loc.description}`;
    if (loc.landmarks) locDesc += ` Landmarks: ${loc.landmarks}`;
    locDesc += "\n";
  }

  // Pre-load all character reference images for per-page injection
  const charWhere: any = { universeId, referenceImageUrl: { not: "" } };
  if (characterIds?.length) {
    charWhere.id = { in: characterIds };
  }
  const refCharacters = await prisma.character.findMany({ where: charWhere });

  const characterRefs = new Map<string, { name: string; data: string; mimeType: string }>();
  for (const char of refCharacters) {
    const img = readImageAsBase64(char.referenceImageUrl);
    if (img) {
      characterRefs.set(char.name.toLowerCase(), {
        name: char.name,
        data: img.data,
        mimeType: img.mimeType,
      });
    }
  }

  // Build setup message — style guide and scene instructions only, NO reference images
  const setupParts: any[] = [];

  setupParts.push({
    text: `You are illustrating a children's picture book. I will give you scene descriptions one at a time. For each one, generate ONE illustration — a full scene with characters, background, and atmosphere.

IMPORTANT — Read the following style guide carefully. Every illustration you generate MUST follow these rules exactly.

${styleGuide}
CRITICAL: Maintain PERFECT visual consistency across ALL pages:
- Characters must look IDENTICAL on every page (same body, same colors, same outfit, same proportions)
- Locations must look the same when revisited (same landmarks, same colors, same geography)
- Art style, color palette, and lighting approach must stay consistent throughout

CHARACTERS:\n${charDesc}
${locDesc ? `LOCATIONS:\n${locDesc}` : ""}

For each page, I may include character reference images. These are for CHARACTER IDENTITY ONLY:
- Use them to match the character's body shape, colors, proportions, outfit, and accessories
- Do NOT copy the style, pose, layout, background, or artistic technique from the reference images
- Do NOT reproduce the grid/multi-pose layout of reference sheets — generate a SINGLE scene illustration
- The reference images may be in a different art style — IGNORE their style and follow the style guide above instead`,
  });

  debug.image(`Starting multi-turn story chat: ${pages.length} pages, ${characterRefs.size} character refs available`);

  // Create chat session
  const chat = ai.chats.create({
    model: "gemini-2.5-flash-image",
    config: {
      responseModalities: ["Image", "Text"],
      imageConfig: {
        aspectRatio: "4:3",
      },
    },
  });

  // Send setup message (text only, no images)
  try {
    const setupResponse = await chat.sendMessage({
      message: setupParts,
    });
    debug.image("Setup message sent, Gemini acknowledged");
  } catch (e: any) {
    debug.error(`Setup message failed: ${e.message}`);
  }

  // Generate each page — inject only relevant character references
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    if (!page.image_prompt) continue;

    debug.image(`Chat page ${i + 1}/${pages.length}: generating...`, {
      promptPreview: page.image_prompt.slice(0, 80),
    });
    const startTime = Date.now();

    // Attach reference images for characters in this scene
    const pageParts: any[] = [];
    const matchedChars: string[] = [];
    const sceneCharacters = page.characters_in_scene || [];

    if (sceneCharacters.length > 0) {
      // Use explicit character list from Claude
      for (const charName of sceneCharacters) {
        const ref = characterRefs.get(charName.toLowerCase());
        if (ref) {
          pageParts.push({
            inlineData: { data: ref.data, mimeType: ref.mimeType },
          });
          pageParts.push({
            text: `[Reference for ${ref.name} — use for character identity ONLY, not style or layout]`,
          });
          matchedChars.push(ref.name);
        }
      }
    } else {
      // Fallback: search prompt text for character names
      const promptLower = page.image_prompt.toLowerCase();
      for (const [nameLower, ref] of characterRefs) {
        if (promptLower.includes(nameLower)) {
          pageParts.push({
            inlineData: { data: ref.data, mimeType: ref.mimeType },
          });
          pageParts.push({
            text: `[Reference for ${ref.name} — use for character identity ONLY, not style or layout]`,
          });
          matchedChars.push(ref.name);
        }
      }
    }

    // Rotate shot types to force composition variety
    const shotTypes = [
      "WIDE ESTABLISHING SHOT — character small in a big landscape",
      "MEDIUM SHOT — full body with environment visible",
      "CLOSE-UP — face and upper body filling most of the frame",
      "LOW ANGLE — looking up at the character from ground level",
      "OVER-THE-SHOULDER or BIRD'S EYE view",
      "MEDIUM-WIDE — character at one side, environment dominant",
    ];
    const shotType = shotTypes[i % shotTypes.length];

    pageParts.push({
      text: `Page ${page.page_number}: ${page.image_prompt}\n\nFRAMING: Use a ${shotType}. This MUST look different from the previous page — different angle, different composition, different background emphasis.\n\n${ART_STYLE_REMINDER} Generate a SINGLE scene illustration. ${matchedChars.length > 0 ? `Match ${matchedChars.join(" and ")} to their reference images (body, colors, outfit) but use the style guide for art style.` : ""}`,
    });

    try {
      let imageUrl: string | null = null;
      let attempts = 0;
      const maxAttempts = 2;

      while (!imageUrl && attempts < maxAttempts) {
        attempts++;
        const response = await chat.sendMessage({
          message: pageParts,
        });

        imageUrl = extractImage(response);

        if (!imageUrl) {
          // Log detailed response info for debugging
          const candidate = response?.candidates?.[0];
          const textParts = candidate?.content?.parts
            ?.filter((p: any) => p.text)
            ?.map((p: any) => p.text)
            ?.join(" ") || "no content";
          const finishReason = candidate?.finishReason || "no candidate";
          const safetyRatings = candidate?.safetyRatings?.map((r: any) => `${r.category}:${r.probability}`).join(", ") || "none";
          const promptFeedback = response?.promptFeedback?.blockReason || "none";
          debug.error(`Chat page ${i + 1}/${pages.length}: no image (attempt ${attempts}/${maxAttempts}). finishReason=${finishReason}, blockReason=${promptFeedback}, safety=[${safetyRatings}], text="${textParts.slice(0, 200)}", refImages=${matchedChars.length}`);

          if (attempts < maxAttempts) {
            debug.image(`Retrying page ${i + 1}...`);
          }
        }
      }

      if (imageUrl) {
        results.set(page.page_number, imageUrl);
        debug.image(`Chat page ${i + 1}/${pages.length}: done in ${Date.now() - startTime}ms`, { imageUrl });
        onProgress?.(page.page_number, pages.length, imageUrl);
      } else {
        debug.error(`Chat page ${i + 1}/${pages.length}: failed after ${maxAttempts} attempts`);
      }
    } catch (e: any) {
      debug.error(`Chat page ${i + 1}/${pages.length}: failed: ${e.message}`);
    }
  }

  debug.image(`Story chat complete: ${results.size}/${pages.length} images generated`);
  return results;
}
