import { GoogleGenAI } from "@google/genai";
import prisma from "../lib/prisma.js";
import { debug } from "../lib/debug.js";
import { buildImageStyleGuide } from "./imageStyleGuide.js";
import fs from "fs";
import path from "path";
import { randomUUID } from "crypto";

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_AI_KEY });

const IMAGES_DIR = path.resolve("public/images");

if (!fs.existsSync(IMAGES_DIR)) {
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
}

function saveBase64Image(base64Data: string, mimeType: string = "image/png"): string {
  const ext = mimeType.includes("webp") ? "webp" : mimeType.includes("jpeg") ? "jpg" : "png";
  const filename = `${randomUUID()}.${ext}`;
  const filepath = path.join(IMAGES_DIR, filename);
  const buffer = Buffer.from(base64Data, "base64");
  fs.writeFileSync(filepath, buffer);
  return `/images/${filename}`;
}

function readImageAsBase64(imageUrl: string): { data: string; mimeType: string } | null {
  const imgPath = path.join("public", imageUrl);
  if (!fs.existsSync(imgPath)) return null;
  const data = fs.readFileSync(imgPath).toString("base64");
  const ext = path.extname(imgPath).slice(1);
  const mimeType = ext === "webp" ? "image/webp" : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : "image/png";
  return { data, mimeType };
}

/**
 * Extract the generated image from a Gemini response.
 */
function extractImage(response: any): string | null {
  const candidates = response?.candidates;
  if (!candidates?.[0]?.content?.parts) return null;

  for (const part of candidates[0].content.parts) {
    if (part.inlineData?.data) {
      return saveBase64Image(part.inlineData.data, part.inlineData.mimeType || "image/png");
    }
  }
  return null;
}

/**
 * Build reference image parts for Gemini from character and location sheets.
 */
async function buildReferenceParts(
  universeId: string,
  characterIds?: string[]
): Promise<any[]> {
  const parts: any[] = [];

  // Character reference sheets
  const charWhere: any = { universeId, referenceImageUrl: { not: "" } };
  if (characterIds?.length) {
    charWhere.id = { in: characterIds };
  }
  const characters = await prisma.character.findMany({ where: charWhere });

  for (const char of characters) {
    const img = readImageAsBase64(char.referenceImageUrl);
    if (img) {
      parts.push({
        inlineData: { data: img.data, mimeType: img.mimeType },
      });
      parts.push({
        text: `Reference sheet for ${char.name} (${char.speciesOrType}). Body: ${char.appearance}. ${char.outfit ? `Outfit: ${char.outfit}` : ""} ${char.specialDetail ? `Key detail: ${char.specialDetail}` : ""}`,
      });
    }
  }

  // Location reference sheets
  const locations = await prisma.location.findMany({
    where: { universeId, referenceImageUrl: { not: "" } },
  });

  for (const loc of locations) {
    const img = readImageAsBase64(loc.referenceImageUrl);
    if (img) {
      parts.push({
        inlineData: { data: img.data, mimeType: img.mimeType },
      });
      parts.push({
        text: `Reference sheet for location "${loc.name}" (${loc.role}): ${loc.description}`,
      });
    }
  }

  return parts;
}

/**
 * Generate a single character model sheet using Gemini (for regeneration).
 */
export async function generateCharacterSheet(
  characterId: string
): Promise<string> {
  const character = await prisma.character.findUniqueOrThrow({
    where: { id: characterId },
    include: { universe: true },
  });

  debug.image(`Generating character sheet for "${character.name}" via Gemini`);
  const startTime = Date.now();

  const prompt = buildCharacterSheetPrompt(character);
  const parts: any[] = [{ text: prompt }];

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["Image", "Text"],
    },
  });

  debug.image("Gemini response:", {
    candidates: response?.candidates?.length || 0,
    parts: response?.candidates?.[0]?.content?.parts?.length || 0,
    partTypes: response?.candidates?.[0]?.content?.parts?.map((p: any) => p.text ? "text" : p.inlineData ? `image(${p.inlineData.mimeType})` : "unknown").join(", ") || "none",
    finishReason: response?.candidates?.[0]?.finishReason || "unknown",
    text: response?.candidates?.[0]?.content?.parts?.find((p: any) => p.text)?.text?.slice(0, 200) || "none",
  });

  const imageUrl = extractImage(response);
  if (!imageUrl) {
    throw new Error("No image generated by Gemini for character sheet");
  }

  await prisma.character.update({
    where: { id: characterId },
    data: { referenceImageUrl: imageUrl },
  });

  debug.image(`Character sheet for "${character.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
  return imageUrl;
}

/**
 * Generate ALL character sheets for a universe. Each character gets its
 * own independent Gemini call to prevent visual blending between characters.
 * Style consistency is maintained via identical style guide text in each prompt.
 */
export async function generateAllCharacterSheets(
  universeId: string
): Promise<void> {
  const characters = await prisma.character.findMany({
    where: { universeId },
    include: { universe: true },
    orderBy: { role: "asc" }, // main first
  });

  if (characters.length === 0) return;

  debug.image(`Generating ${characters.length} character sheets (separate sessions)`);

  for (let i = 0; i < characters.length; i++) {
    const character = characters[i];

    if (character.referenceImageUrl) {
      debug.image(`"${character.name}" already has sheet, skipping`);
      continue;
    }

    debug.image(`Sheet ${i + 1}/${characters.length}: generating for "${character.name}"`);
    const startTime = Date.now();

    const prompt = buildCharacterSheetPrompt(character);

    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: {
          responseModalities: ["Image", "Text"],
        },
      });

      const imageUrl = extractImage(response);
      if (!imageUrl) {
        debug.error(`No image in Gemini response for "${character.name}"`);
        continue;
      }

      await prisma.character.update({
        where: { id: character.id },
        data: { referenceImageUrl: imageUrl },
      });

      debug.image(`Sheet for "${character.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
    } catch (e: any) {
      debug.error(`Sheet failed for "${character.name}": ${e.message}`);
    }
  }

  debug.image("All character sheets generated");
}

/**
 * Build the prompt text for a character model sheet.
 */
function buildCharacterSheetPrompt(character: any): string {
  const outfitSection = character.outfit
    ? `\nOUTFIT (character is ALWAYS wearing/carrying ALL of these):\n${character.outfit}`
    : "";

  return `CRITICAL: DO NOT draw outlines. DO NOT draw borders around shapes. DO NOT use linework.

ART STYLE — oil pastel on textured paper:
- Medium: Oil pastel illustration on heavy textured paper. Soft, waxy, chalky strokes that blend and smudge into each other. Colors are rich, saturated, and slightly grainy.
- Edges: ABSOLUTELY NO outlines, linework, or drawn borders. Shapes are formed by pressing colored pastel into paper — edges are soft, smudgy, and blended where colors meet. Like finger-painting with crayons.
- Texture: Heavy visible paper grain showing through the pastel. Strokes should look thick, waxy, and layered. Areas of color should be uneven and organic with visible stick marks.
- Colors: Bold, warm, saturated. Oil pastel gives rich opaque color with a slight sheen. Colors blend where they overlap, creating soft transitions.
- Feel: Handmade, warm, tactile, childlike. Like illustrations a talented art teacher would make. Think Komako Sakai or Miroco Machiko.
- FORBIDDEN: outlines, linework, ink borders, cel shading, anime style, vector art, digital art, 3D rendering, photorealism, sharp drawn contours.

REPEAT: NO OUTLINES. NO LINEWORK. Shapes are defined by COLOR ONLY.

Create a page of OIL PASTEL PAINTED STUDIES of this character. Show this character 12-15 times on a warm cream-colored paper background. Mix of full body views and close-up head/upper body views. Each study should look like an individual oil pastel painting — soft, smudgy, painterly. NOT a clean technical model sheet. NOT a cartoon turnaround. These are PAINTED STUDIES, like pages from an artist's sketchbook done entirely in oil pastel.

IMPORTANT: This character is a ${character.speciesOrType}. Follow the body description below EXACTLY. This character has its own unique body shape, colors, proportions, and clothing.

CHARACTER: ${character.name}
SPECIES: ${character.speciesOrType}

BODY (follow this description precisely — this defines what the character looks like):
${character.appearance}
${outfitSection}
SPECIAL DETAIL: ${character.specialDetail}

Include:
- Full body: front, side, back, 3/4, running, sitting, reaching
- Close-up: happy, sad, surprised, determined, laughing

CONSISTENCY: The character must look identical in every study. Same proportions, colors, features. All clothing/accessories visible in every view. Wings, tails, antennae never disappear. Head shape stays the same in close-ups.

ONE character painted many times in oil pastel. NOT multiple characters. NOT outlined cartoon art.`;
}

/**
 * Generate a location reference sheet using Gemini.
 */
export async function generateLocationSheet(
  locationId: string,
  previousSheetUrls: string[] = []
): Promise<string> {
  const location = await prisma.location.findUniqueOrThrow({
    where: { id: locationId },
    include: { universe: true },
  });

  const moods = ["gentle", "funny", "exciting", "mysterious"];
  const randomMood = moods[Math.floor(Math.random() * moods.length)];
  const styleGuide = buildImageStyleGuide(
    randomMood,
    location.universe.illustrationStyle
  );

  debug.image(`Generating location sheet for "${location.name}" via Gemini`);
  const startTime = Date.now();

  const prompt = `CRITICAL: DO NOT draw outlines. DO NOT draw borders around shapes. DO NOT use linework.

ART STYLE: Oil pastel on heavy textured paper. Soft, waxy, chalky strokes that blend and smudge. NO outlines, NO linework, NO drawn borders — shapes formed by pressing colored pastel into paper, edges soft and smudgy. Heavy paper grain, thick layered strokes, visible stick marks. Bold warm saturated colors. Handmade and childlike, not precise. Think Komako Sakai. FORBIDDEN: outlines, linework, ink borders, cel shading, vector art, digital art, 3D, photorealism.

Create a LOCATION REFERENCE SHEET. Show this location 8-10 times on a plain white background.

LOCATION: ${location.name}
ROLE: ${location.role}
DESCRIPTION: ${location.description}
LIGHTING: ${location.lighting}
KEY LANDMARKS (must appear every time): ${location.landmarks}

Include:
- Wide panoramic view
- Medium view at character scale
- Close-up of key landmark
- Morning light version
- Afternoon/golden hour version
- Night/dusk version
- View from approaching
- View from inside/center looking out

CONSISTENCY: Same landmarks, geography, and colors across all views. No characters. Environment only.

ONE location shown from many angles and times of day. NOT multiple locations.`;

  const parts: any[] = [];

  for (const sheetUrl of previousSheetUrls) {
    const img = readImageAsBase64(sheetUrl);
    if (img) {
      parts.push({ inlineData: { data: img.data, mimeType: img.mimeType } });
    }
  }

  if (previousSheetUrls.length > 0) {
    parts.push({
      text: `The images above are reference sheets from the same book. Match their exact art style.`,
    });
  }

  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["Image", "Text"],
    },
  });

  const imageUrl = extractImage(response);
  if (!imageUrl) {
    throw new Error("No image generated by Gemini for location sheet");
  }

  await prisma.location.update({
    where: { id: locationId },
    data: { referenceImageUrl: imageUrl },
  });

  debug.image(`Location sheet for "${location.name}" done in ${Date.now() - startTime}ms: ${imageUrl}`);
  return imageUrl;
}

/**
 * Generate ALL scene illustrations for a story using a single multi-turn
 * chat session. Gemini maintains character, scenery, and style consistency
 * across all pages because they're generated in the same conversation.
 *
 * Flow:
 * 1. First message: all character/location reference sheets + style guide
 * 2. Each subsequent message: one page's scene prompt → one illustration
 */
export async function generateStoryImages(
  universeId: string,
  characterIds: string[],
  mood: string,
  pages: { page_number: number; image_prompt: string }[],
  onProgress?: (pageNum: number, total: number, imageUrl: string) => void
): Promise<Map<number, string>> {
  const styleGuide = buildImageStyleGuide(mood);
  const results = new Map<number, string>();

  // Build character descriptions
  const characters = await prisma.character.findMany({
    where: { universeId, id: { in: characterIds } },
  });

  let charDesc = "";
  for (const char of characters) {
    charDesc += `${char.name} (${char.speciesOrType}): ${char.appearance}`;
    if (char.outfit) charDesc += `. Outfit: ${char.outfit}`;
    if (char.specialDetail) charDesc += `. ${char.specialDetail}`;
    charDesc += "\n";
  }

  // Build location descriptions
  const locations = await prisma.location.findMany({ where: { universeId } });
  let locDesc = "";
  for (const loc of locations) {
    locDesc += `${loc.name}: ${loc.description}`;
    if (loc.landmarks) locDesc += ` Landmarks: ${loc.landmarks}`;
    locDesc += "\n";
  }

  // Build the setup message with all reference images
  const setupParts: any[] = [];

  setupParts.push({
    text: `You are illustrating a children's picture book. I will give you scene descriptions one at a time. For each one, generate ONE illustration.

IMPORTANT — Read the following style guide carefully. Every illustration you generate MUST follow these rules exactly.

${styleGuide}
CRITICAL: Maintain PERFECT visual consistency across ALL pages:
- Characters must look IDENTICAL on every page (same body, same colors, same outfit, same proportions)
- Locations must look the same when revisited (same landmarks, same colors, same geography)
- Art style, color palette, and lighting approach must stay consistent throughout

CHARACTERS:\n${charDesc}
${locDesc ? `LOCATIONS:\n${locDesc}` : ""}`,
  });

  // Add all character reference sheet images
  const refParts = await buildReferenceParts(universeId, characterIds);
  setupParts.push(...refParts);

  setupParts.push({
    text: `The images above are character and location reference sheets. Draw the characters EXACTLY as shown — same body, proportions, colors, outfit, and accessories in every illustration. Now I will send you scene descriptions one at a time. Generate one illustration per scene.`,
  });

  debug.image(`Starting multi-turn story chat: ${pages.length} pages, ${refParts.filter(p => p.inlineData).length} reference images`);

  // Create chat session
  const chat = ai.chats.create({
    model: "gemini-2.5-flash-image",
    config: {
      responseModalities: ["Image", "Text"],
      imageConfig: {
        aspectRatio: "4:3",
      },
    },
  });

  // Send setup message
  try {
    const setupResponse = await chat.sendMessage({
      message: setupParts,
    });
    debug.image("Setup message sent, Gemini acknowledged");
  } catch (e: any) {
    debug.error(`Setup message failed: ${e.message}`);
    // Continue anyway — some models don't respond to setup messages
  }

  // Generate each page
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    if (!page.image_prompt) continue;

    debug.image(`Chat page ${i + 1}/${pages.length}: generating...`, {
      promptPreview: page.image_prompt.slice(0, 80),
    });
    const startTime = Date.now();

    try {
      const response = await chat.sendMessage({
        message: `Page ${page.page_number}: ${page.image_prompt}\n\nReminder: Oil pastel style — soft waxy smudgy strokes, NO outlines, NO linework. Characters must match their reference sheets exactly.`,
      });

      const imageUrl = extractImage(response);
      if (imageUrl) {
        results.set(page.page_number, imageUrl);
        debug.image(`Chat page ${i + 1}/${pages.length}: done in ${Date.now() - startTime}ms`, { imageUrl });
        onProgress?.(page.page_number, pages.length, imageUrl);
      } else {
        debug.error(`Chat page ${i + 1}/${pages.length}: no image in response`);
      }
    } catch (e: any) {
      debug.error(`Chat page ${i + 1}/${pages.length}: failed: ${e.message}`);
    }
  }

  debug.image(`Story chat complete: ${results.size}/${pages.length} images generated`);
  return results;
}
